WToanLee.Web/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WToanLee.Web.Models
{
    public class ProductViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }

        public string Alias { get; set; }

        public int CategoryID { get; set; }

        public string Image { get; set; }
        public string MoreImage { get; set; }

        public decimal Price { get; set; }
        public decimal? PromotionPrice { get; set; }
        public int? Warranty { get; set; }

        public string Description { get; set; }

        public string Content { get; set; }

        //
        public bool? HomeFlag { get; set; }

        public bool? HotFlag { get; set; }
        public int? ViewCount { get; set; }

        public DateTime? CreateDate { get; set; }

        public string CreateBy { get; set; }

        public DateTime? UpdateDate { get; set; }

        public string UpdateBy { get; set; }
        public bool Status { get; set; }
        public string MetaKeyWord { get; set; }

        public string MetaDesciption { get; set; }

        public string Tags { get; set; }

        public int Quantity { get; set; }

        public virtual IEnumerable<ProductTagViewModel> ProductTags { get; set; }

        public virtual ProductCategoryViewModel ProductCategories { get; set; }
    }
}

WToanLee.Web/Controllers/ProductController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Web.Common;
using Web.Models.Models;
using Web.Service;
using WToanLee.Web.Infrastructure.Core;
using WToanLee.Web.Models;

namespace WToanLee.Web.Controllers
{
    public class ProductController : Controller
    {
        private ICommonService _commonService;
        private IProductService _iproductServive;
        private IProductCategoryService _productCategoryService;

        public ProductController(ICommonService commonService, IProductService productService, IProductCategoryService productCategoryService)
        {
            _commonService = commonService;
            _iproductServive = productService;
            _productCategoryService = productCategoryService;
        }

        // GET: Product
        public ActionResult Detail(int id)
        {
            var product = _iproductServive.GetById(id);
            var productViewModel = Mapper.Map<Product, ProductViewModel>(product);
            var relateProduct = _iproductServive.GetReatedProduct(id, 5);
            ViewBag.RelateProduc = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(relateProduct);
            //

            List<string> moreImage;
            if (!string.IsNullOrEmpty(productViewModel.MoreImage))
            {
                moreImage = new JavaScriptSerializer().Deserialize<List<string>>(productViewModel.MoreImage);
            }
            else
            {
                moreImage = new List<string>();
            }

            ViewBag.MoreImage = moreImage;
            ViewBag.Tag = Mapper.Map<IEnumerable<Tag>, IEnumerable<TagViewModel>>(_iproductServive.GetListTagProductID(id));
            //
            //List<string> moreImage = new JavaScriptSerializer().Deserialize<List<string>>(productViewModel.MoreImage);
            //ViewBag.MoreImage = moreImage;
            return View(productViewModel);
        }

        public ActionResult Category(int id, int page = 1, string sort = "")
        {
            // appSeting
            int pageSize = int.Parse(ConfigHelper.GetByKey("PageSize"));
            int totalRow = 0;
            var productModel = _iproductServive.GetListProductByCategoryIdPage(id, page, pageSize, sort, out totalRow);
            var productViewModel = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(productModel);
            // tinh tong so trang
            int totalPage = (int)Math.Ceiling((double)totalRow / pageSize);
            // call doi tuong page
            var category = _productCategoryService.GetById(id);
            ViewBag.Category = Mapper.Map<ProductCategorye, ProductCategoryViewModel>(category);
            var paginationSet = new PagenationSet<ProductViewModel>()
            {
                Items = productViewModel,
                MaxPage = int.Parse(ConfigHelper.GetByKey("MaxPage")),
                Page = page,
                TotalCount = totalRow,
                TotalPage = totalPage
            };
            return View(paginationSet);
        }

        // TRANG TÌM KIẾM
        public ActionResult Search(string keyword , int page = 1, string sort = "")
        {
            // appSeting
            int pageSize = int.Parse(ConfigHelper.GetByKey("PageSize"));
            int totalRow = 0;
            var productModel = _iproductServive.Search(keyword, page, pageSize, sort, out totalRow);
            var productViewModel = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(productModel);
            // tinh tong so trang
            int totalPage = (int)Math.Ceiling((double)totalRow / pageSize);
            // call doi tuong page
            ViewBag.keyword = keyword;
            var paginationSet = new PagenationSet<ProductViewModel>()
            {
                Items = productViewModel,
                MaxPage = int.Parse(ConfigHelper.GetByKey("MaxPage")),
                Page = page,
                TotalCount = totalRow,
                TotalPage = totalPage
            };
            return View(paginationSet);
        }
        public JsonResult GetListProductByName(string keyword)
        {
            var model = _iproductServive.GetListProductByName(keyword);
            return Json(new
            {
                data = model
            }, JsonRequestBehavior.AllowGet);
        }

        // TRANG LẤY RA DANH SÁCH TAG

        public ActionResult ListByTag(string tagid , int page = 1) {
            // appSeting
            int pageSize = int.Parse(ConfigHelper.GetByKey("PageSize"));
            int totalRow = 0;
            var productModel = _iproductServive.GetListProductByTag(tagid, page, pageSize, out totalRow);
            var productViewModel = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(productModel);
            // tinh tong so trang
            int totalPage = (int)Math.Ceiling((double)totalRow / pageSize);
            // call doi tuong page
            ViewBag.Tag = Mapper.Map<Tag, TagViewModel>(_iproductServive.getTag(tagid));
            var paginationSet = new PagenationSet<ProductViewModel>()
            {
                Items = productViewModel,
                MaxPage = int.Parse(ConfigHelper.GetByKey("MaxPage")),
                Page = page,
                TotalCount = totalRow,
                TotalPage = totalPage
            };
            return View(paginationSet);
        }
    }
}

WToanLee.Web/Controllers/QRCodeController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZXing;

namespace WToanLee.Web.Controllers
{
    public class QRCodeController : Controller
    {
        // GET: QRCode
        public ActionResult GenerateQRCode(string data)
        {
            // Sử dụng thư viện ZXing để tạo QR code từ dữ liệu
            BarcodeWriter barcodeWriter = new BarcodeWriter();
            barcodeWriter.Format = BarcodeFormat.QR_CODE;
            Bitmap bitmap = barcodeWriter.Write(data);

            // Chuyển đổi Bitmap thành mảng byte để hiển thị trong trang web
            ImageConverter converter = new ImageConverter();
            byte[] imageBytes = (byte[])converter.ConvertTo(bitmap, typeof(byte[]));

            // Trả về hình ảnh dưới dạng file hình ảnh
            return File(imageBytes, "image/png");
        }

        public ActionResult QRCodeDetail(string link)
        {
            ViewBag.data = link;
            return View();
        }

    }
}

WToanLee.Web/Views/Product/Category.cshtml
@model WToanLee.Web.Infrastructure.Core.PagenationSet<WToanLee.Web.Models.ProductViewModel>

@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/Layouts.cshtml";
    var category = (WToanLee.Web.Models.ProductCategoryViewModel)ViewBag.Category;
}

<div class="women-product">
    @if (Model.Count > 0)
    {
        <div class=" w_content">
            <div class="women">
                <a href="/@(category.Alias)-p-@(category.ID)"><h4><span>@Model.TotalCount Sản phẩm</span> </h4></a>
                <ul class="w_nav">
                    <li>Sắp Xếp : </li>
                    <li><a class="active" href="?@Model.Page&sort=popular">Phổ biến</a></li> |
                    <li><a href="?@Model.Page&sort=new">Mới </a></li> |
                    <li><a href="?@Model.Page&sort=discount">Giảm giá</a></li> |
                    <li><a href="?@Model.Page&sort=price">Giá: Thấp -> Cao </a></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="clearfix"> </div>
            </div>
        </div>
        <!-- grids_of_4 -->
        <div class="grid-product">
            @foreach (var product in Model.Items)
            {
                var url = "/" + product.Alias + "-p-" + product.ID;
                <div class="product-grid">
                    <div class="content_box">
                        <a href="@url">
                            <div class="left-grid-view grid-view-left">
                                <img src="@product.Image" class="img-responsive watch-right" alt="@product.Name" />
                                <div class="mask">
                                    <div class="info">Xem nhanh</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <h4><a href="@url">@product.Name</a></h4>
                    <p>@product.Description</p>
                    @(product.Price == 0 ? "Liên Hện " : product.Price.ToString("N0"))
                </div>
            }

            <div class="clearfix"> </div>
            @if (Model.TotalPage > 1)
            {
                var startPageIndex = Math.Max(1, Model.Page - Model.MaxPage / 2);
                var endPageIndex = Math.Min(Model.TotalPage, Model.Page + Model.MaxPage / 2);
                <nav>
                    <ul class="pagination">
                        @if (Model.Page > 1)
                        {
                            <li>
                                <a href="?page=1" aria-label="First">
                                    <i class="fa fa-angle-double-left"></i>
                                </a>
                            </li>
                            <li>
                                <a href="?page=@(Model.Page-1)" aria-label="Previous">
                                    <i class="fa fa-angle-double-left"></i>
                                </a>
                            </li>
                        }

                        @for (int i = startPageIndex; i <= endPageIndex; i++)
                        {
                            if (Model.Page == i)
                            {
                                <li class="active"><a href="?page=@i" title="Trang @i">@i</a></li>
                            }
                            else
                            {
                                <li><a href="?page=@i" title="Trang @i">@i</a></li>
                            }
                        }
                        @if (Model.Page < Model.TotalPage)
                        {
                            <li>
                                <a href="?page=@(Model.Page+1)" aria-label="Next">
                                    <i class="fa fa-angle-double-right"></i>
                                </a>
                            </li>
                            <li>
                                <a href="?page=@Model.TotalPage" aria-label="Last">
                                    <i class="fa fa-angle-double-right"></i>
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
            }



        </div>}
    else
    {
        <div class="text-center">Không có sản phẩm nào được tìm thấy !!</div>
    }

</div>

WToanLee.Web/Views/Product/Detail.cshtml
@model WToanLee.Web.Models.ProductViewModel

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/Layouts.cshtml";
}
@section FooterJS{
    <script type="text/javascript" src="~/Assets/client/js/jquery.flexisel.js"></script>
}
<div class=" single_top">
    <div class="single_grid">
        <div class="grid images_3_of_2">
            <ul id="etalage">
                <li>
                    <a href="optionallink.html">
                        <img class="etalage_thumb_image img-responsive" src="@Model.Image" />
                    </a>
                </li>
                @{
                    var listMoreImage = (List<string>)ViewBag.MoreImage;
                    if (listMoreImage != null)
                    {
                        foreach (var image in listMoreImage)
                        {
                            <li>
                                <img class="etalage_thumb_image img-responsive" src="@image" />
                            </li>
                        }
                    }
                }
            </ul>
            <div class="clearfix"> </div>
        </div>
        <div class="desc1 span_3_of_2">

            <h4>@Model.Name</h4>
            <div class="cart-b">
                <div class="left-n ">@(Model.Price == 0 ? "Tìm hiểu sản phẩm " : Model.Price.ToString("N0"))</div>
                <a class="now-get get-cart-in" href="/them-go-hang/@Model.ID">Thêm Giỏ Hàng</a>
                <div class="clearfix"></div>
            </div>
            <h6>Còn @Model.Quantity trong kho hàng</h6>
            <p>@Model.Description</p>
            <div class="share">
                <h5><font color="red">TAG :</font></h5>
                <ul class="">
                    @foreach (var tag in (IEnumerable<WToanLee.Web.Models.TagViewModel>)ViewBag.Tag)
                    {
                        <li><a href="/tag/@(tag.ID)/html"><strong><font color="orange">@tag.Name</font></strong></a></li>
                    }
                </ul>
                <h5><font color="red">Chia sẻ :</font></h5>
                <ul class="share_nav">
                    <li><a href="#"><img src="~/Assets/client/images/facebook.png" title="facebook"></a></li>
                    <li><a href="#"><img src="~/Assets/client/images/twitter.png" title="Twiiter"></a></li>
                    <li><a href="#"><img src="~/Assets/client/images/rss.png" title="Rss"></a></li>
                    <li><a href="#"><img src="~/Assets/client/images/gpluse.png" title="Google+"></a></li>
                </ul>
            </div>
        </div>
        <div class="clearfix"> </div>
    </div>
    @{
        var relateProduct = (IEnumerable<WToanLee.Web.Models.ProductViewModel>)ViewBag.RelateProduc;
    }
    <ul id="flexiselDemo1">
        @if (relateProduct != null)
        {
            foreach (var product in relateProduct)
            {
                <li><img src="@product.Image" /><div class="grid-flex"><a href="/ @(product.Alias) -p-@( product.ID)">Bloch</a><p>@product.Price</p></div></li>
            }
        }
    </ul>
    <script type="text/javascript">
        $(window).load(function () {
            $("#flexiselDemo1").flexisel({
                visibleItems: 5,
                animationSpeed: 1000,
                autoPlay: true,
                autoPlaySpeed: 3000,
                pauseOnHover: true,
                enableResponsiveBreakpoints: true,
                responsiveBreakpoints: {
                    portrait: {
                        changePoint: 480,
                        visibleItems: 1
                    },
                    landscape: {
                        changePoint: 640,
                        visibleItems: 2
                    },
                    tablet: {
                        changePoint: 768,
                        visibleItems: 3
                    }
                }
            });

        });
    </script>

    <div class="toogle">
        <h3 class="m_3"><font color="red">Chi Tiết Sản Phẩm</font></h3>
        <p class="m_text">@Html.Raw(Model.Content)</p>

        <h2>Tao QR cho trang</h2>
        <h3>Bấm vào đây</h3>
        <img src="@Url.Action("GenerateQRCode", "QRCode", new { data = $"https://www.facebook.com/profile.php?id=100012600577147" })" alt="QR Code" />

        <form action="@Url.Action("QRCodeDetail", "QRCode")" method="get">
            <!-- Thêm một input hidden để truyền tham số -->
            <input type="hidden" name="link" value="facebook.com" />
            <!-- Thêm một nút bấm với type="submit" -->
            <button type="submit">Bấm Vào để lấy QR</button>
        </form>

    </div>

</div>

WToanLee.Web/Views/Product/ListByTag.cshtml
@model WToanLee.Web.Infrastructure.Core.PagenationSet<WToanLee.Web.Models.ProductViewModel>

@{
    var tag = (WToanLee.Web.Models.TagViewModel)ViewBag.Tag;
    ViewBag.Title = "Kết quả tìm kiếm cho từ khóa " + tag.Name;
    Layout = "~/Views/Shared/Layouts.cshtml";
}

<div class="women-product">
    @if (Model.Count > 0)
    {
        <div class=" w_content">
            <div class="women">
                <a href="#"><h4><span>Kết quả tìm kiếm : @tag </span> </h4></a>
                <div class="clearfix"> </div>
            </div>
        </div>
        <!-- grids_of_4 -->
        <div class="grid-product">
            @foreach (var product in Model.Items)
            {
                var url = "/" + product.Alias + "-p-" + product.ID;
                <div class="product-grid">
                    <div class="content_box">
                        <a href="@url">
                            <div class="left-grid-view grid-view-left">
                                <img src="@product.Image" class="img-responsive watch-right" alt="@product.Name" />
                                <div class="mask">
                                    <div class="info">Xem nhanh</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <h4><a href="@url">@product.Name</a></h4>
                    <p>@product.Description</p>
                    @(product.Price == 0 ? "Liên Hện " : product.Price.ToString("N0"))
                </div>
            }

            <div class="clearfix"> </div>
            @if (Model.TotalPage > 1)
            {
                var startPageIndex = Math.Max(1, Model.Page - Model.MaxPage / 2);
                var endPageIndex = Math.Min(Model.TotalPage, Model.Page + Model.MaxPage / 2);
                <nav>
                    <ul class="pagination">
                        @if (Model.Page > 1)
                        {
                            <li>
                                <a href="?page=1" aria-label="First">
                                    <i class="fa fa-angle-double-left"></i>
                                </a>
                            </li>
                            <li>
                                <a href="?page=@(Model.Page-1)" aria-label="Previous">
                                    <i class="fa fa-angle-double-left"></i>
                                </a>
                            </li>
                        }

                        @for (int i = startPageIndex; i <= endPageIndex; i++)
                        {
                            if (Model.Page == i)
                            {
                                <li class="active"><a href="?page=@i" title="Trang @i">@i</a></li>
                            }
                            else
                            {
                                <li><a href="?page=@i" title="Trang @i">@i</a></li>
                            }
                        }
                        @if (Model.Page < Model.TotalPage)
                        {
                            <li>
                                <a href="?page=@(Model.Page+1)" aria-label="Next">
                                    <i class="fa fa-angle-double-right"></i>
                                </a>
                            </li>
                            <li>
                                <a href="?page=@Model.TotalPage" aria-label="Last">
                                    <i class="fa fa-angle-double-right"></i>
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
            }



        </div>}
    else
    {
        <div class="text-center">Không có sản phẩm nào được tìm thấy !!</div>
    }

</div>

WToanLee.Web/Views/Product/Search.cshtml
@model WToanLee.Web.Infrastructure.Core.PagenationSet<WToanLee.Web.Models.ProductViewModel>

@{
    var keyword = (string)ViewBag.keyword;
    ViewBag.Title = "Kết quả tìm kiếm cho từ khóa " + keyword;
    Layout = "~/Views/Shared/Layouts.cshtml";
}

<div class="women-product">
    @if (Model.Count > 0)
    {
        <div class=" w_content">
            <div class="women">
                <a href="#"><h4><span>Kết quả tìm kiếm : @keyword</span> </h4></a>
                <ul class="w_nav">
                    <li>Sắp Xếp : </li>
                    <li><a class="active" href="?@Model.Page&sort=popular">Phổ biến</a></li> |
                    <li><a href="?@Model.Page&sort=new">Mới </a></li> |
                    <li><a href="?@Model.Page&sort=discount">Giảm giá</a></li> |
                    <li><a href="?@Model.Page&sort=price">Giá: Thấp -> Cao </a></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="clearfix"> </div>
            </div>
        </div>
        <!-- grids_of_4 -->
        <div class="grid-product">
            @foreach (var product in Model.Items)
            {
                var url = "/" + product.Alias + "-p-" + product.ID;
                <div class="product-grid">
                    <div class="content_box">
                        <a href="@url">
                            <div class="left-grid-view grid-view-left">
                                <img src="@product.Image" class="img-responsive watch-right" alt="@product.Name" />
                                <div class="mask">
                                    <div class="info">Xem nhanh</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <h4><a href="@url">@product.Name</a></h4>
                    <p>@product.Description</p>
                    @(product.Price == 0 ? "Liên Hện " : product.Price.ToString("N0"))
                </div>
            }

            <div class="clearfix"> </div>
            @if (Model.TotalPage > 1)
            {
                var startPageIndex = Math.Max(1, Model.Page - Model.MaxPage / 2);
                var endPageIndex = Math.Min(Model.TotalPage, Model.Page + Model.MaxPage / 2);
                <nav>
                    <ul class="pagination">
                        @if (Model.Page > 1)
                        {
                            <li>
                                <a href="?page=1" aria-label="First">
                                    <i class="fa fa-angle-double-left"></i>
                                </a>
                            </li>
                            <li>
                                <a href="?page=@(Model.Page-1)" aria-label="Previous">
                                    <i class="fa fa-angle-double-left"></i>
                                </a>
                            </li>
                        }

                        @for (int i = startPageIndex; i <= endPageIndex; i++)
                        {
                            if (Model.Page == i)
                            {
                                <li class="active"><a href="?page=@i" title="Trang @i">@i</a></li>
                            }
                            else
                            {
                                <li><a href="?page=@i" title="Trang @i">@i</a></li>
                            }
                        }
                        @if (Model.Page < Model.TotalPage)
                        {
                            <li>
                                <a href="?page=@(Model.Page+1)" aria-label="Next">
                                    <i class="fa fa-angle-double-right"></i>
                                </a>
                            </li>
                            <li>
                                <a href="?page=@Model.TotalPage" aria-label="Last">
                                    <i class="fa fa-angle-double-right"></i>
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
            }



        </div>}
    else
    {
        <div class="text-center">Không có sản phẩm nào được tìm thấy !!</div>
    }

</div>