WToanLee.Web/Controllers/HomeClientController.cs
using AutoMapper;
using System.Collections.Generic;
using System.Web.Mvc;
using Web.Models.Models;
using Web.Service;
using WToanLee.Web.Models;

namespace WToanLee.Web.Controllers
{
    public class HomeClientController : Controller
    {
        private IProductCategoryService _iproducCategoryService;
        private ICommonService _commonService;
        private IProductService  _iproductServive;

        public HomeClientController(IProductCategoryService productCategoryService , ICommonService commonService , IProductService productService)
        {
            _iproducCategoryService = productCategoryService;
            _commonService = commonService;
            _iproductServive = productService;
        }

        // GET: HomeClient
        public ActionResult Index()
        {
            var slideModel = _commonService.GetSlide();
            var slideView = Mapper.Map<IEnumerable<Slide>, IEnumerable<SlideViewModel>>(slideModel);
            var homeViewModel = new HomeViewModel();
            homeViewModel.Slides = slideView;

            var lasttestProductModel = _iproductServive.GetLastest(2);
            var topSaleProductModel = _iproductServive.GetHotProduct(2);
            var lasttestProductViewModel = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(lasttestProductModel);
            var topSaleProductViewModel = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(topSaleProductModel);
            homeViewModel.lastestProduct = lasttestProductViewModel;
            homeViewModel.topSaleProduct = topSaleProductViewModel;
            return View(homeViewModel);
        }

        [ChildActionOnly]
        public ActionResult Footer()
        {
            var model = _iproducCategoryService.GetAll();
            var listProductCategoryViewModel = Mapper.Map<IEnumerable<ProductCategorye>, IEnumerable<ProductCategoryViewModel>>(model);
            return PartialView(listProductCategoryViewModel);
        }

        [ChildActionOnly]
        public ActionResult Header()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public ActionResult Category()
        {
            var model = _iproducCategoryService.GetAll();
            var listProductCategoryViewModel = Mapper.Map<IEnumerable<ProductCategorye>, IEnumerable<ProductCategoryViewModel>>(model);
            return PartialView(listProductCategoryViewModel);
        }

        public ActionResult Login()
        {
            return View();
        }
    }
}

WToanLee.Web/Views/Shared/Category.cshtml
@model IEnumerable<WToanLee.Web.Models.ProductCategoryViewModel>
<div class="sub-cate">
    <div class=" top-nav rsidebar span_1_of_left">
        <h3 class="cate"><font color="pink">DANH MỤC SẢN PHẨM</font></h3>
        <ul class="menu">
            @foreach (var category in Model.Where(x => x.ParentID == null))
            {
                var url = "/" + category.Alias + "-pc-" + category.ID;
                var chilCategoryes = Model.Where(x => x.ParentID == category.ID);
                <li class="item1">
                    @*@(chilCategoryes.Count() > 0 ? "<img class=\"arrow-img\" src=\"~/Assets/client/images/arrow1.png\" alt=\"\"/>" : "")*@
                    <a href="@url"><font color="green">@category.Name </font><img class="arrow-img " src="~/Assets/client/images/arrow1.png" alt="" /> </a>
                    @if (chilCategoryes.Count() > 0)
                    {
                        <ul class="cute">
                            @foreach (var childrenCategory in chilCategoryes)
                            {
                                var urlChildren = "/" + childrenCategory.Alias + "-pc-" + childrenCategory.ID;
                                <li class="subitem1"><a href="@urlChildren"><font color="black">@childrenCategory.Name</font> </a></li>
                            }
                        </ul>
                    }
                </li>
            }
        </ul>
    </div>
    <!--initiate accordion-->
    <script type="text/javascript">
        $(function () {
            var menu_ul = $('.menu > li > ul'),
                menu_a = $('.menu > li > a');
            menu_ul.hide();
            menu_a.click(function (e) {
                e.preventDefault();
                if (!$(this).hasClass('active')) {
                    menu_a.removeClass('active');
                    menu_ul.filter(':visible').slideUp('normal');
                    $(this).addClass('active').next().stop(true, true).slideDown('normal');
                } else {
                    $(this).removeClass('active');
                    $(this).next().stop(true, true).slideUp('normal');
                }
            });

        });
    </script>
    <div class="chain-grid menu-chain">
        <a href="single.html"><img class="img-responsive chain" src="~/Assets/client/images/panda.png" alt=" " /></a>
        <div class="grid-chain-bottom chain-watch">
            <span class="actual dolor-left-grid">300$</span>
            <span class="reducedfrom">500$</span>
            <h6><a href="single.html">Gấu May Mắn</a></h6>
        </div>
    </div>
    <a class="view-all all-product" href="product.html"><font color="red">TẤT CẢ SẢN PHẨM</font><span> </span></a>
</div>

WToanLee.Web/Views/Shared/Footer.cshtml
@model IEnumerable<WToanLee.Web.Models.ProductCategoryViewModel>
<div class="footer">
    <div class="footer-top">
        <div class="container">
            <div class="latter">
                <h6><font color="red">NHẬN THÔNG TIN</font></h6>
                <div class="sub-left-right">
                    <form>
                        <input type="text" value="Nhập Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter email here';}" />
                        <input type="submit" value="Gửi Đi" />
                    </form>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="latter-right">
                <p>Theo Dõi</p>
                <ul class="face-in-to">
                    <li><a href="#"><span> </span></a></li>
                    <li><a href="https://www.facebook.com/profile.php?id=100014497275622"><span class="facebook-in"> </span></a></li>
                    <div class="clearfix"> </div>
                </ul>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="footer-bottom-cate">
                <h6><font color="orange">DANH MỤC</font></h6>
                <ul>
                    @if (Model != null)
                    {
                        foreach (var produccategory in Model)
                        {
                            <li><a href="#">@produccategory.Name</a></li>
                        }
                    }

                </ul>
            </div>
            <div class="footer-bottom-cate bottom-grid-cat">
                <h6><font color="orange">DỰ ÁN TIÊU BIỂU</font></h6>
                <ul>
                    <li><a href="#">Cửa hàng đồ chơi</a></li>
                    <li><a href="#">Thiết kế trang sức</a></li>
                    <li><a href="#">Máy in 3D</a></li>
                    <li><a href="#">Làm đẹp thú cưng</a></li>
                    <li><a href="#">Đồ chơi lắp ghép</a></li>
                    <li><a href="#">Vòng tay trang sức</a></li>
                </ul>
            </div>
            <div class="footer-bottom-cate">
                <h6><font color="orange">TOP NHÃN HÀNG</font></h6>
                <ul>
                    <li><a href="#">TPT Store</a></li>
                    <li><a href="#">ToanLee Store</a></li>
                    <li><a href="#">Tales Store</a></li>
                </ul>
            </div>
            <div class="footer-bottom-cate cate-bottom">
                <h6><font color="orange">ĐỊA CHỈ</font></h6>
                <ul>
                    <li>Nam Từ Liêm </li>
                    <li>Hà Nội</li>
                    <li class="phone">PH : 0355725203</li>
                    <li class="temp"> <p class="footer-class">Thiết kế bởi<a href="https://www.facebook.com/profile.php?id=100014497275622" target="_blank"> ToanLee</a> </p></li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

WToanLee.Web/Views/Shared/Header.cshtml
<div class="header">
    <div class="top-header">
        <div class="container">
            <div class="top-header-left">
                <ul class="support">
                    <li><a href="#"><label> </label></a></li>
                    <li><a href="#">24x7 Trực tiếp<span class="live"> hỗ trợ</span></a></li>
                </ul>
                <ul class="support">
                    <li class="van"><a href="#"><label> </label></a></li>
                    <li><a href="#">Miễn phí giao hàng <span class="live">với đơn hàng trên 500</span></a></li>
                </ul>
                <div class="clearfix"> </div>
            </div>
            <div class="top-header-right">
                <div class="down-top">
                    <select class="in-drop">
                        <option value="English" class="in-of">Tiếng việt</option>
                        <option value="Japanese" class="in-of">Tiếng anh</option>
                        <option value="French" class="in-of">Tiếng nhật</option>
                        <option value="German" class="in-of">Tiếng Trung</option>
                    </select>
                </div>
                <div class="down-top top-down">
                    <select class="in-drop">

                        <option value="Dollar" class="in-of">Dollar</option>
                        <option value="Yen" class="in-of">VND</option>
                        <option value="Euro" class="in-of">Euro</option>
                    </select>
                </div>
                <!---->
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="bottom-header">
        <div class="container">
            <div class="header-bottom-left">
                <div class="logo">
                    <a href="home"> <img src="~/Assets/client/images/ToanLee.png" /></a>
                </div>
                <div class="search">
                    <form method="get" action="/tim-kiem">
                        <input type="text" id="txtKeyword" name="keyword" placeholder="Từ khóa">
                        <input type="submit" value="Tìm Kiếm" id="btnSearch">
                    </form>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="header-bottom-right">
                <div class="account"><a href="login.html"><span> </span>Tài Khoản</a></div>
                <ul class="login">
                    <li><a href="/page-login"><span> </span>Đăng Nhập</a></li> |
                    <li><a href="register.html">Đăng Xuất</a></li>
                </ul>
                <div class="cart"><a href="#"><span> </span>Giỏ Hàng</a></div>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

WToanLee.Web/Views/Shared/Layouts.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Big shope A Ecommerce Category Flat Bootstarp Resposive Website Template | Home :: w3layouts</title>
    <link href="~/Assets/client/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/bower_components/jquery-ui/themes/smoothness/jquery-ui.min.css" rel="stylesheet" />
    <!--theme-style-->
    <link href="~/Assets/client/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!--//fonts-->
    <script src="~/Assets/client/js/jquery.min.js"></script>
</head>
<body>
    @{ Html.RenderAction("Header", "HomeClient");}

    <div class="container">
        @RenderBody()
        @{ Html.RenderAction("Category", "HomeClient");}
    </div>
    @{ Html.RenderAction("Footer", "HomeClient");}
    <div class="clearfix"> </div>
    <script src="~/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/Assets/client/js/common.js"></script>
    <!--script-->

    @RenderSection("FooterJS", required: false)
</body>
</html>